apiVersion: v1
kind: Pod
metadata:
  name: cowsay-env
spec:
  containers:
  - image: smlinux/cowsay:env
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: cowsay
          key: interval
#      value: "1"
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /webdata

  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80

  volumes:
  - name: html
    emptyDir: {}

