apiVersion: v1
kind: Pod 
metadata:
  name: deployment-reader
  namespace: kube-system
  labels:
    app: deployment-reader
spec:
  serviceAccountName: pod-reader 
  containers:
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.10.4
    command:
    - sh
    - -c
    - |
      while true
      do
        echo "check deployment..."
        kubectl get deployment --all-namespaces
        sleep 30
      done
