apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myapp
    type: back-end
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - name: appjs
    image: smlinux/appjs
    ports:
    - containerPort: 8080
      protocol: TCP

